variables:
  ANSIBLE_PATH: "cicd/platform/config"
  FRONTEND_IMAGE: "fr3m3n/workbench-front"
  FRONTEND_TAG: "$CI_COMMIT_TAG"
  BACKEND_IMAGE: "fr3m3n/workbench-back"
  BACKEND_TAG: "$CI_COMMIT_TAG"

stages:
  - prepare_tf              # [Terraform] pipeline
  - validate_tf
  - plan_tf
  - deploy_tf
  - destroy_tf
  - configure_infra         # [Ansible] job
  - upload_to_dockerhub     # [DinD] job
  - push_to_remote          # [Ansible] job

include:
  - local: '/_cicd/deploy_infrastructure.yml'
  - local: '/_cicd/configure_infrastructure.yml'
  - local: '/_cicd/deploy_app.yml'