version: '3.8'
services:
  frontend:
    build: ./front
    image: ${FRONTEND_IMAGE}:${FRONTEND_TAG}
    ports:
      - "3000:80"
    networks:
      - media-network

  backend:
    build: ./back
    image: ${BACKEND_IMAGE}:${BACKEND_TAG}
    ports:
      - "8080:8080"
    networks:
      - media-network

networks:
  media-network:
    driver: bridge
