stages:
  - build_frontend
  - build_backend


build_frontend_image:
  stage: build_frontend
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  # before_script:
  #   - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t $FRONTEND_IMAGE:$FRONTEND_TAG ./front --no-cache
    - docker push $FRONTEND_IMAGE:$FRONTEND_TAG
  only:
    refs:
      - tags
    changes:
      - front/*

build_backend_image:
  stage: build_backend
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  # before_script:
  #   - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker build -t $BACKEND_IMAGE:$BACKEND_TAG ./back --no-cache
    - docker push $BACKEND_IMAGE:$BACKEND_TAG
  only:
    refs:
      - tags
    changes:
      - back/*
