stages:
  - build_frontend
  - build_backend

build_frontend_image:
  stage: build_frontend
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  script:
    - |
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q "front/**/*"; then
        docker build -t $FRONTEND_IMAGE:$FRONTEND_TAG ./front --no-cache
        docker push $FRONTEND_IMAGE:$FRONTEND_TAG
      else
        echo "No changes in 'front/' directory, skipping build."
      fi
  rules:
    - if: '$CI_COMMIT_TAG'


build_backend_image:
  stage: build_backend
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  script:
    - |
      if git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep -q "back/**/*"; then
        docker build -t $BACKEND_IMAGE:$BACKEND_TAG ./back --no-cache
        docker push $BACKEND_IMAGE:$BACKEND_TAG
      else
        echo "No changes in 'back/' directory, skipping build."
      fi
  rules:
    - if: '$CI_COMMIT_TAG'

