stages:
  # - build_frontend
  - build_backend

build_backend_image:
  stage: build_backend
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
  script:
    - docker build -t $BACKEND_IMAGE:$BACKEND_TAG ./back --no-cache
    - docker push $BACKEND_IMAGE:$BACKEND_TAG
  rules:
    - if: '$CI_COMMIT_TAG'
      changes:
        - back/**/*