stages:
  - configure_infra

configure_aws_infrastructure:
  stage: configure_infra
  image: alpinelinux/ansible:latest
  dependencies:
    - build_aws_infrastructure
  before_script:
    - ansible --version
    - echo "Initialize Ansible configuration..."
    - cd $ANSIBLE_PATH
    - chmod 400 $SSH_KEY
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i hosts.ini config_infra.yml --private-key=$SSH_KEY -u ubuntu
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - _cicd/infra/config/config_infra.yml
