variables:
  IMAGE_TAG: $CI_COMMIT_TAG
  # URL-safe slug of the branch + unique id of the current pipeline 
  # IMAGE_TAG combines the branch/tag slug and the pipeline ID.


stages:
  - upload_to_dockerhub
  # - push_to_remote


build_docker_image:
  stage: upload_to_dockerhub
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker-compose build --no-cache
    - docker-compose push
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - back/*
        - front/*

deploy_docker_aws:
  stage: push_to_remote
  image: alpinelinux/ansible:latest
  dependencies:
    - deploy_aws_infrastructure
  before_script:
    - cd $ANSIBLE_PATH
    - chmod 400 $SSH_KEY
    # - EC2_PUBLIC_IP=$(cat $ANSIBLE_PATH/ec2_ip.txt)  # Read the IP address into a variable
  script: 
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i hosts.ini start_app.yml --private-key=$SSH_KEY -u ubuntu
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - back/*
        - front/*