stages:
  - deploy_frontend
  - deploy_backend

deploy_front_to_aws:
  stage: deploy_frontend
  image: alpinelinux/ansible:latest
  before_script:
    - apk add --no-cache git # Make sure git is installed
    - git clone --single-branch --branch deployment-branch https://gitlab.com/frem3n/media-workbench.git temp_repo
    - mv temp_repo/_cicd/infra/config/hosts.ini .
    - rm -rf temp_repo # Clean up
    - cd $ANSIBLE_PATH
    - chmod 400 $SSH_KEY
  script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i hosts.ini pull_front.yml --private-key=$SSH_KEY -u ubuntu
  rules:
    - if: '$CI_COMMIT_TAG =~ /frontend/'

deploy_back_to_aws:
  stage: deploy_backend
  image: alpinelinux/ansible:latest
  before_script:
    - apk add --no-cache git # Make sure git is installed
    - git clone --single-branch --branch deployment-branch https://gitlab.com/frem3n/media-workbench.git temp_repo
    - mv temp_repo/_cicd/infra/config/hosts.ini .
    - rm -rf temp_repo # Clean up
    - cd $ANSIBLE_PATH
    - chmod 400 $SSH_KEY
  script: 
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook -i hosts.ini pull_back.yml --private-key=$SSH_KEY -u ubuntu
  rules:
    - if: '$CI_COMMIT_TAG =~ /backend/'
